interface Props {
    register: any;
    errors?: any;
}

export default function WorkExperience(props: Props) {
    return (
        <div className="table-responsive">
            <table className="table table-borderless">
                <thead>
                <tr>
                    <th>Desde</th>
                    <th>Hasta</th>
                    <th>Nombre de la empresa</th>
                    <th>Dirección de la empresa</th>
                    <th>Teléfono de la empresa</th>
                    <th>Función que desempeñó</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience1-from')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience1-to')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1-companyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1-companyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1-companyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1-jobFunction')}
                        />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience2-from')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience2-to')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2-companyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2-companyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2-companyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2-jobFunction')}
                        />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience3-from')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience3-to')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3-companyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3-companyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3-companyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3-jobFunction')}
                        />
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    )
}
