interface Props {
    register: any;
    errors?: any;
}

export default function WorkExperience(props: Props) {
    return (
        <div className="table-responsive">
            <table className="table table-borderless">
                <thead>
                <tr>
                    <th>Desde</th>
                    <th>Hasta</th>
                    <th>Nombre de la empresa</th>
                    <th>Dirección de la empresa</th>
                    <th>Teléfono de la empresa</th>
                    <th>Función que desempeñó</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience1From')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience1To')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1CompanyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1CompanyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1CompanyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience1JobFunction')}
                        />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience2From')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience2To')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2CompanyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2CompanyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2CompanyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience2JobFunction')}
                        />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience3From')}
                        />
                    </td>
                    <td>
                        <input
                            type="date"
                            className="form-control"
                            {...props.register('experience3To')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3CompanyName')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3CompanyAddress')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3CompanyPhone')}
                        />
                    </td>
                    <td>
                        <input
                            type="text"
                            className="form-control"
                            {...props.register('experience3JobFunction')}
                        />
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    )
}
