import { InscriptionCommand } from "../domain/InscriptionCommand";

export const transformInscriptionToStudent = (inscription: InscriptionCommand) => {
  return {
		type : inscription.type,
    trainingId: inscription.trainingId,
    certificateId: inscription.certificateId,
    isCerficateAssiten: false,
    isVerifiy: true,
    fechaAceptacion: new Date(),
    isActive: true,
    isComplete: true,
    pdfRequisitos: inscription.requirementsPDF,
    document: inscription.document,
    name: inscription.name,
    lastName: inscription.lastName,
    birthdate: new Date(inscription.birthdate),
    direction: inscription.direction,
    province: inscription.province,
    city: inscription.city,
    phone: inscription.phone,
    celphone: inscription.celphone,
    email: inscription.email,
    primaria: {
      name: inscription.primaryInstitutionName,
      pais: inscription.primaryCountry,
      ciudad: inscription.primaryCity,
      titulo: inscription.primaryDegree,
    },
    secundaria: {
      name: inscription.secondaryInstitutionName,
      pais: inscription.secondaryCountry,
      ciudad: inscription.secondaryCity,
      titulo: inscription.secondaryDegree,
    },
    tecnico: {
      name: inscription.technicalInstitutionName,
      pais: inscription.technicalCountry,
      ciudad: inscription.technicalCity,
      titulo: inscription.technicalDegree,
    },
    tercerNivel: {
      name: inscription.tertiaryInstitutionName,
      pais: inscription.tertiaryCountry,
      ciudad: inscription.tertiaryCity,
      titulo: inscription.tertiaryDegree,
    },
    cuartoNivel: {
      name: inscription.quaternaryInstitutionName,
      pais: inscription.quaternaryCountry,
      ciudad: inscription.quaternaryCity,
      titulo: inscription.quaternaryDegree,
    },
    capacitacion1: {
      nameCourse: inscription.course1NameCourse,
      nameInstitucion: inscription.course1InstitutionName,
      dateCourse: new Date(inscription.course1DateCourse),
      hourCourse: inscription.course1HourCourse,
    },
    capacitacion2: {
      nameCourse: inscription.course2NameCourse,
      nameInstitucion: inscription.course2InstitutionName,
      dateCourse: new Date(inscription.course2DateCourse),
      hourCourse: inscription.course2HourCourse,
    },
    capacitacion3: {
      nameCourse: inscription.course3NameCourse,
      nameInstitucion: inscription.course3InstitutionName,
      dateCourse: new Date(inscription.course3DateCourse),
      hourCourse: inscription.course3HourCourse,
    },
    experiencia1: {
      desde: new Date(inscription.experience1From),
      hasta: new Date(inscription.experience1To),
      name: inscription.experience1CompanyName,
      direction: inscription.experience1CompanyAddress,
      phone: inscription.experience1CompanyPhone,
      funcion: inscription.experience1JobFunction,
    },
    experiencia2: {
      desde: new Date(inscription.experience2From),
      hasta: new Date(inscription.experience2To),
      name: inscription.experience2CompanyName,
      direction: inscription.experience2CompanyAddress,
      phone: inscription.experience2CompanyPhone,
      funcion: inscription.experience2JobFunction,
    },
    experiencia3: {
      desde: new Date(inscription.experience3From),
      hasta: new Date(inscription.experience3To),
      name: inscription.experience3CompanyName,
      direction: inscription.experience3CompanyAddress,
      phone: inscription.experience3CompanyPhone,
      funcion: inscription.experience3JobFunction,
    },
    autoidentificacion: inscription.experience3Autoidentificacion,
    tipoOcupacion: inscription.tipoOcupacion,
    contrato: inscription.contrato,
    seguroMedio: inscription.workingConditionsSeguroMedico,
    sueldoTrece: inscription.sueldoTrece,
    sueldoCatorce: inscription.sueldoCatorce,
    sueldo: inscription.sueldo,
    cambioPuesto: inscription.cambioPuesto,
    satisfechoEmpleo: inscription.satisfechoEmpleo,
    agotadoEmpleo: inscription.agotadoEmpleo,
    respetanTrabajo: inscription.respetanTrabajo,
    jefesRecoTrab: inscription.jefesReconocenTrabajo,
    riesgoLaboral: inscription.riesgosLaborales,
    deseariaCambiarTrabajo: inscription.deseaCambiarTrabajo,
    seguroMedico: inscription.livingConditionsSeguroMedico,
    hijos: inscription.hijos,
    cuantoHijos: inscription.cuantoHijos,
    hijosMayorTres: inscription.hijosMayorTres,
    estudian: inscription.estudian,
    miembrosHogar: inscription.miembrosHogar,
    propiedad: inscription.propiedad,
    servicioBasico: inscription.servicioBasico,
    discapacidad: inscription.discapacidad,
    tipoDiscapacidad: inscription.tipoDiscapacidad,
    socioEmpleo: inscription.socioEmpleo,
  };
};
